---
title: "Project 2-regression"
author: "Rue Ekpemiro"
date: "2025-05-26"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,        
  message = FALSE,    # hide package messages
  warning = FALSE,    # hide warnings
  results = 'hide'    # hide printed output from code
)
```

```{r}
athelete <- read.csv("C:/Users/oekpe/OneDrive/Desktop/STA 108/projects/athelete.csv")
```

Summary of Data:
```{r}
#Scatter plots

library(patchwork)
library(ggplot2)
a <- ggplot(athelete,aes(lbm,rcc)) + geom_point(shape = 19) + ggtitle("Lean body mass v. red blood cell count") + xlab("Lean body mass in kg") + ylab("Red blood cell count per liter")
b <- ggplot(athelete,aes(bmi,rcc)) + geom_point(shape = 19) + ggtitle("Body mass index v. red blood cell count") + xlab("body mass index in kg") + ylab("Red blood cell count per liter")
c <- ggplot(athelete,aes(pcBfat,rcc)) + geom_point(shape = 19) + ggtitle("Perfecent body fat v. red blood cell count") + xlab("Percent body fat") + ylab("Red blood cell count per liter")
d <- ggplot(athelete,aes(ferr,rcc)) + geom_point(shape = 19) + ggtitle("Plasma ferritins v. red blood cell count") + xlab("Plasma ferritins in ng") + ylab("Red blood cell count per liter")
(a+b)/(c+d)
```

```{r}
#Correlation Matrix

n.data <- subset(athelete, select = -c(6,7))

library(corrplot)
datamatrix <- cor(n.data)
corrplot(datamatrix,method = "number")

```

```{r}
# Boxplots
e <- ggplot(athelete, aes(y=rcc, x = sex))+ geom_boxplot() + ylab("Red blood cell count per liter")+ xlab("Sex") + ggtitle("Red blood cell count by Sex") + coord_flip()
f <- ggplot(athelete, aes(y=rcc, x = newsport))+ geom_boxplot() + ylab("Red blood cell count per liter")+ xlab("Sport") + ggtitle("Red blood cell count by sport-type") + coord_flip()
e+f
```
```{r}
#full model fit
full.model <- lm(rcc~.,athelete)
full.model

#Summary Table of full model
library(gt)
library(webshot2)
z <- coef(summary(full.model))         
z_df <- as.data.frame(z)
z_df$Term <- rownames(z_df)            
rownames(z_df) <- NULL                 
gt_table <- gt(z_df) |> 
  cols_move_to_start(columns = Term) |> 
  tab_header(
    title = "Table 1: Summary of Full Regression Model"
  )|> 
  fmt_number(columns = where(is.numeric), decimals = 4)
gtsave(gt_table, "table.png")

summary(full.model)
```
Forward selection using BIC criteria
```{r}
full.model = lm(rcc~., athelete)
empty.model = lm(rcc~1, athelete)

n = nrow(athelete)
library(MASS)

forward.model.BIC = stepAIC(empty.model, scope = list(lower = empty.model, upper= full.model), k = log(n),direction = "forward")
forward.model.BIC$coefficients
```

final model
```{r}
final.model <- lm(rcc~sex+newsport, athelete)

#Summary Table of final model
w <- coef(summary(final.model))         
w_df <- as.data.frame(w)
w_df$Term <- rownames(w_df)            
rownames(w_df) <- NULL                 
gt_table <- gt(w_df) |> 
  cols_move_to_start(columns = Term) |> 
  tab_header(
    title = "Table 2: Summary of Final Regression Model"
  )|> 
  fmt_number(columns = where(is.numeric), decimals = 4)
gtsave(gt_table, "table2.png")

summary(full.model)
```

Diagnostics
```{r}
#Outlier Detection
alpha = 0.05
n = nrow(athelete)
t.cutoff= qt(1-alpha/(2), n-2)
t.cutoff

rij = rstandard(final.model)
CO.rij = which(abs(rij) > t.cutoff)
CO.rij
```
```{r}
new.data <- athelete[, c("rcc", "sex", "newsport")]

```

```{r}
best.model <- final.model
ei.s = best.model$residuals/sqrt(sum(best.model$residuals^2)/(nrow(new.data) - length(best.model$coefficients)))

ri = rstandard(best.model)

ti = rstudent(best.model)

par(mfrow =c(2,2))

hist(ei.s,main ="Semi-studentized/standardized residuals")
hist(ri,main="Studentized/Standardized residuals")
hist(ti, main="Deleted Residuals")

# identify outliers

alpha = 0.1 ; n = nrow(new.data); p = length(best.model$coefficients)
cutoff = qt(1-alpha/(2*n), n -p )
cutoff

cutoff.deleted = qt(1-alpha/(2*n), n -p -1 )
cutoff.deleted

outliers = which(abs(ei.s)> cutoff | abs(ri) > cutoff | abs(ti) > cutoff.deleted)
outliers

n.data <- new.data[-outliers,]
```

```{r}
n.model <- lm(rcc~sex+newsport, n.data)
#qqplot
qqnorm(n.model$residuals)
qqline(n.model$residuals, col ='red')
#Shapiro-Wilk test
ei = n.model$residuals
the.SWtest = shapiro.test(ei)
the.SWtest

```
```{r}
n.data$ei = n.model$residuals
n.data$yhat = n.model$fitted.values

qplot(yhat, ei, data = n.data) + ggtitle("Errors vs. Fitted Values") + xlab("Fitted Values") +
ylab("Errors") + geom_hline(yintercept = 0,col = "purple")

ei = n.model$residuals
Group = rep("Lower",nrow(n.data)) #Creates a vector that repeats "Lower" n times
Group[n.data$rcc > median(n.data$rcc)] = "Upper"
Group = as.factor(Group) #Changes it to a factor, which R recognizes as a grouping variable.
n.data$Group = Group
#the.FKtest= fligner.test(data.Hair$ei, data.Hair$Group)
#the.FKtest
library(car)
the.BFtest = leveneTest(ei~Group, data=n.data, center=median)
the.BFtest
```
Multiple Cis

```{r}
mult.fun = function(n,p,g,alpha){
  bon = qt(1-alpha/(2*g), n-p)
  WH = sqrt(p*qf(1-alpha,p,n-p))
  Sch = sqrt(g*qf(1-alpha,g,n-p))
  all.mul = c(bon,WH,Sch)
  all.mul = round(all.mul,3)
  names(all.mul) = c("Bon","WH","Sch")
  return(all.mul)
}

mult.CI = function(C.star,x.stars,the.model,alpha,the.type = "confidence"){
  all.preds = predict(the.model,x.stars)
  if(the.type == "confidence"){
    all.se = predict(the.model,x.stars,interval = the.type,se.fit = TRUE)$se.fit
  } else if(the.type == "prediction"){
    all.se = predict(the.model,x.stars,interval = the.type,se.fit = TRUE)$se.fit
    MSE = sum(the.model$residuals^2)/(length(the.model$residuals) - length(the.model$coefficients))
    all.se = sqrt(all.se^2 + MSE)
  }
  LB = all.preds - C.star*all.se
  UB = all.preds + C.star*all.se
  all.CIs = cbind(LB,UB)
  colnames(all.CIs) = paste((1-alpha)*100, "%",c(" Lower"," Upper"), sep = "")
  results = cbind(all.preds,all.CIs)
  colnames(results)[1] = "Estimate"
  return(results)
}
```

Finding Multiplier
```{r}
all.of.them = mult.fun(nrow(n.data), length(n.model$coefficients), 3, 0.05)
all.of.them
```

```{r}
alpha =0.05
SCI =confint(n.model,level = 1-alpha/3)
SCI
SCI_df <- as.data.frame(SCI)

# Rownames as columns
SCI_df$Term <- rownames(SCI_df)
SCI_df <- SCI_df[, c("Term", names(SCI_df)[1:2])]  

# Make the table
table_gt <- gt(SCI_df) %>%
  tab_header(title = "Table 3: Simultaneous Confidence Intervals") %>%
  fmt_number(columns = 2:3, decimals = 4)
gtsave(table_gt, filename = "SCI_table.png")
```
\clearpage

```{r, ref.label=knitr::all_labels()[knitr::all_labels() != "setup"], echo=TRUE, eval=FALSE}
```

